version: '3'
services:
  postgres:
    build: ./db
    container_name: "tl3_db"
    volumes:
      - ${PWD}/db/data:/volume
    ports:
      - "5550:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=tl3
      - PGDATA=/volume/data

  nginx:
    image: nginx:1.15
    restart: always
    container_name: "nginx"
    ports:
      - "8000:80"
    volumes:
      - ./balancer:/etc/nginx/conf.d:ro
    depends_on:
      - login
    
  login:
    build: ./src/login
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
